services:
  bazaar-api:
    build: 
      context: .
      dockerfile: Bazaar.app/Dockerfile 
    container_name: bazaar-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8091:8080"
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./wwwroot/ads:/app/wwwroot/ads
      - ./wwwroot/temp:/app/wwwroot/temp
      - ./wwwroot/banners:/app/wwwroot/banners
      - ./wwwroot/telegram:/app/wwwroot/telegram

    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: uniceps-api_default